/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new customer account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description User registered successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example Jane Doe */
                                name: string;
                                /** @example jane.doe@example.com */
                                email: string;
                                /**
                                 * @example customer
                                 * @enum {string}
                                 */
                                type: "admin" | "customer";
                            };
                        };
                    };
                };
                /** @description Email is already registered */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in and receive a bearer JWT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Signed in successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                user: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                    _id: string;
                                    /** @example Jane Doe */
                                    name: string;
                                    /** @example jane.doe@example.com */
                                    email: string;
                                    /**
                                     * @example customer
                                     * @enum {string}
                                     */
                                    type: "admin" | "customer";
                                    cart: {
                                        product: {
                                            /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                            _id: string;
                                            /** @example Wireless Mouse */
                                            title: string;
                                            /** @example 799 */
                                            price: number;
                                            /** @example https://example.com/images/mouse.jpg */
                                            imageURL: string;
                                            /** @example 25 */
                                            stock: number;
                                        };
                                        /** @example 2 */
                                        quantity: number;
                                    }[];
                                    addresses: {
                                        /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                        _id: string;
                                        /** @example 221B Baker Street */
                                        addressLine1: string;
                                        /** @example London */
                                        city: string;
                                        /** @example Greater London */
                                        state: string;
                                        /** @example 560001 */
                                        pincode: string;
                                        /**
                                         * @example home
                                         * @enum {string}
                                         */
                                        tag?: "home" | "office" | "work";
                                        /** @example true */
                                        isDefault: boolean;
                                    }[];
                                    /** @example 2026-01-15T10:00:00.000Z */
                                    createdAt: string;
                                    /** @example 2026-01-15T10:00:00.000Z */
                                    updatedAt: string;
                                };
                                /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                                token: string;
                            };
                        };
                    };
                };
                /** @description Invalid email or password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out (invalidates the current JWT via tokenVersion bump) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed out successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user fetched successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                _id: string;
                                /** @example Jane Doe */
                                name: string;
                                /** @example jane.doe@example.com */
                                email: string;
                                /**
                                 * @example customer
                                 * @enum {string}
                                 */
                                type: "admin" | "customer";
                                cart: {
                                    product: {
                                        /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                        _id: string;
                                        /** @example Wireless Mouse */
                                        title: string;
                                        /** @example 799 */
                                        price: number;
                                        /** @example https://example.com/images/mouse.jpg */
                                        imageURL: string;
                                        /** @example 25 */
                                        stock: number;
                                    };
                                    /** @example 2 */
                                    quantity: number;
                                }[];
                                addresses: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                    _id: string;
                                    /** @example 221B Baker Street */
                                    addressLine1: string;
                                    /** @example London */
                                    city: string;
                                    /** @example Greater London */
                                    state: string;
                                    /** @example 560001 */
                                    pincode: string;
                                    /**
                                     * @example home
                                     * @enum {string}
                                     */
                                    tag?: "home" | "office" | "work";
                                    /** @example true */
                                    isDefault: boolean;
                                }[];
                                /** @example 2026-01-15T10:00:00.000Z */
                                createdAt: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                updatedAt: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password-reset OTP */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description OTP generated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /**
                                 * @description Dev and test only. Omitted in production, where the OTP is written to the server log instead.
                                 * @example 482913
                                 */
                                otp?: string;
                                /** @example 10 */
                                expiresInMinutes: number;
                            };
                        };
                    };
                };
                /** @description User not found with this email */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password using the OTP from /users/forgot-password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        otp: string;
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description Password reset successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: unknown;
                        };
                    };
                };
                /** @description Invalid or expired OTP */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description User not found with this email */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password while authenticated */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        currentPassword: string;
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description Password changed successfully, returns a new token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                user: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                    _id: string;
                                    /** @example Jane Doe */
                                    name: string;
                                    /** @example jane.doe@example.com */
                                    email: string;
                                    /**
                                     * @example customer
                                     * @enum {string}
                                     */
                                    type: "admin" | "customer";
                                    cart: {
                                        product: {
                                            /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                            _id: string;
                                            /** @example Wireless Mouse */
                                            title: string;
                                            /** @example 799 */
                                            price: number;
                                            /** @example https://example.com/images/mouse.jpg */
                                            imageURL: string;
                                            /** @example 25 */
                                            stock: number;
                                        };
                                        /** @example 2 */
                                        quantity: number;
                                    }[];
                                    addresses: {
                                        /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                        _id: string;
                                        /** @example 221B Baker Street */
                                        addressLine1: string;
                                        /** @example London */
                                        city: string;
                                        /** @example Greater London */
                                        state: string;
                                        /** @example 560001 */
                                        pincode: string;
                                        /**
                                         * @example home
                                         * @enum {string}
                                         */
                                        tag?: "home" | "office" | "work";
                                        /** @example true */
                                        isDefault: boolean;
                                    }[];
                                    /** @example 2026-01-15T10:00:00.000Z */
                                    createdAt: string;
                                    /** @example 2026-01-15T10:00:00.000Z */
                                    updatedAt: string;
                                };
                                token: string;
                            };
                        };
                    };
                };
                /** @description Current password is incorrect */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's addresses */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Addresses fetched successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                _id: string;
                                /** @example 221B Baker Street */
                                addressLine1: string;
                                /** @example London */
                                city: string;
                                /** @example Greater London */
                                state: string;
                                /** @example 560001 */
                                pincode: string;
                                /**
                                 * @example home
                                 * @enum {string}
                                 */
                                tag?: "home" | "office" | "work";
                                /** @example true */
                                isDefault: boolean;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Add a new address (max 4 per user) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        addressLine1: string;
                        city: string;
                        state: string;
                        pincode: string;
                        /** @enum {string} */
                        tag?: "home" | "office" | "work";
                        isDefault?: boolean;
                    };
                };
            };
            responses: {
                /** @description Address added successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                _id: string;
                                /** @example 221B Baker Street */
                                addressLine1: string;
                                /** @example London */
                                city: string;
                                /** @example Greater London */
                                state: string;
                                /** @example 560001 */
                                pincode: string;
                                /**
                                 * @example home
                                 * @enum {string}
                                 */
                                tag?: "home" | "office" | "work";
                                /** @example true */
                                isDefault: boolean;
                            };
                        };
                    };
                };
                /** @description Maximum of 4 addresses allowed, or invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/addresses/{addressId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an address */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Address id */
                    addressId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Address deleted successfully, returns remaining addresses */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                _id: string;
                                /** @example 221B Baker Street */
                                addressLine1: string;
                                /** @example London */
                                city: string;
                                /** @example Greater London */
                                state: string;
                                /** @example 560001 */
                                pincode: string;
                                /**
                                 * @example home
                                 * @enum {string}
                                 */
                                tag?: "home" | "office" | "work";
                                /** @example true */
                                isDefault: boolean;
                            }[];
                        };
                    };
                };
                /** @description Address not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update an address */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Address id */
                    addressId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        addressLine1?: string;
                        city?: string;
                        state?: string;
                        pincode?: string;
                        /** @enum {string} */
                        tag?: "home" | "office" | "work";
                        isDefault?: boolean;
                    };
                };
            };
            responses: {
                /** @description Address updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                _id: string;
                                /** @example 221B Baker Street */
                                addressLine1: string;
                                /** @example London */
                                city: string;
                                /** @example Greater London */
                                state: string;
                                /** @example 560001 */
                                pincode: string;
                                /**
                                 * @example home
                                 * @enum {string}
                                 */
                                tag?: "home" | "office" | "work";
                                /** @example true */
                                isDefault: boolean;
                            };
                        };
                    };
                };
                /** @description Address not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/users/me/addresses/{addressId}/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set an address as the default */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Address id */
                    addressId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default address updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                _id: string;
                                /** @example 221B Baker Street */
                                addressLine1: string;
                                /** @example London */
                                city: string;
                                /** @example Greater London */
                                state: string;
                                /** @example 560001 */
                                pincode: string;
                                /**
                                 * @example home
                                 * @enum {string}
                                 */
                                tag?: "home" | "office" | "work";
                                /** @example true */
                                isDefault: boolean;
                            };
                        };
                    };
                };
                /** @description Address not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's cart */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cart fetched successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                product: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                    _id: string;
                                    /** @example Wireless Mouse */
                                    title: string;
                                    /** @example 799 */
                                    price: number;
                                    /** @example https://example.com/images/mouse.jpg */
                                    imageURL: string;
                                    /** @example 25 */
                                    stock: number;
                                };
                                /** @example 2 */
                                quantity: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Add a product to the cart (or increase its quantity) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        productId: string;
                        /** @default 1 */
                        quantity?: number;
                    };
                };
            };
            responses: {
                /** @description Item added to cart successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: unknown;
                        };
                    };
                };
                /** @description Requested quantity exceeds available stock */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Clear the entire cart */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cart cleared successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                product: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                    _id: string;
                                    /** @example Wireless Mouse */
                                    title: string;
                                    /** @example 799 */
                                    price: number;
                                    /** @example https://example.com/images/mouse.jpg */
                                    imageURL: string;
                                    /** @example 25 */
                                    stock: number;
                                };
                                /** @example 2 */
                                quantity: number;
                            }[];
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a product from the cart */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product id */
                    productId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Item removed from cart successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: unknown;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update the quantity of a cart item */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product id */
                    productId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        quantity: number;
                    };
                };
            };
            responses: {
                /** @description Cart item updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: unknown;
                        };
                    };
                };
                /** @description Requested quantity exceeds available stock */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Product not found in cart */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's orders */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default 1) */
                    page?: string;
                    /** @description Items per page (default 10, max 100) */
                    limit?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Orders fetched successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                orders: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3b */
                                    _id: string;
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                    userId: string;
                                    items: {
                                        /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                        product: string;
                                        /** @example Wireless Mouse */
                                        title: string;
                                        /** @example 799 */
                                        price: number;
                                        /** @example https://example.com/images/mouse.jpg */
                                        imageURL: string;
                                        /** @example 2 */
                                        quantity: number;
                                    }[];
                                    /** @example 1598 */
                                    totalAmount: number;
                                    shippingAddress: {
                                        /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                        addressId: string;
                                        /** @example 221B Baker Street */
                                        addressLine1: string;
                                        /** @example London */
                                        city: string;
                                        /** @example Greater London */
                                        state: string;
                                        /** @example 560001 */
                                        pincode: string;
                                        /**
                                         * @example home
                                         * @enum {string}
                                         */
                                        tag?: "home" | "office" | "work";
                                    };
                                    /** @example 2026-01-15T10:00:00.000Z */
                                    createdAt: string;
                                    /** @example 2026-01-15T10:00:00.000Z */
                                    updatedAt: string;
                                }[];
                                pagination: {
                                    /** @example 42 */
                                    total: number;
                                    /** @example 1 */
                                    page: number;
                                    /** @example 10 */
                                    limit: number;
                                    /** @example 5 */
                                    totalPages: number;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Place an order from the current cart */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        addressId: string;
                    };
                };
            };
            responses: {
                /** @description Order placed successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3b */
                                _id: string;
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                userId: string;
                                items: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                    product: string;
                                    /** @example Wireless Mouse */
                                    title: string;
                                    /** @example 799 */
                                    price: number;
                                    /** @example https://example.com/images/mouse.jpg */
                                    imageURL: string;
                                    /** @example 2 */
                                    quantity: number;
                                }[];
                                /** @example 1598 */
                                totalAmount: number;
                                shippingAddress: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                    addressId: string;
                                    /** @example 221B Baker Street */
                                    addressLine1: string;
                                    /** @example London */
                                    city: string;
                                    /** @example Greater London */
                                    state: string;
                                    /** @example 560001 */
                                    pincode: string;
                                    /**
                                     * @example home
                                     * @enum {string}
                                     */
                                    tag?: "home" | "office" | "work";
                                };
                                /** @example 2026-01-15T10:00:00.000Z */
                                createdAt: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description Cart is empty, or insufficient stock, or no saved addresses */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Address not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single order by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Order id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order fetched successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3b */
                                _id: string;
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                userId: string;
                                items: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                    product: string;
                                    /** @example Wireless Mouse */
                                    title: string;
                                    /** @example 799 */
                                    price: number;
                                    /** @example https://example.com/images/mouse.jpg */
                                    imageURL: string;
                                    /** @example 2 */
                                    quantity: number;
                                }[];
                                /** @example 1598 */
                                totalAmount: number;
                                shippingAddress: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                    addressId: string;
                                    /** @example 221B Baker Street */
                                    addressLine1: string;
                                    /** @example London */
                                    city: string;
                                    /** @example Greater London */
                                    state: string;
                                    /** @example 560001 */
                                    pincode: string;
                                    /**
                                     * @example home
                                     * @enum {string}
                                     */
                                    tag?: "home" | "office" | "work";
                                };
                                /** @example 2026-01-15T10:00:00.000Z */
                                createdAt: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description Order not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse the public product catalog */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default 1) */
                    page?: string;
                    /** @description Items per page (default 10, max 100) */
                    limit?: string;
                    /** @description Searches title and description */
                    search?: string;
                    sortBy?: "title" | "price" | "date";
                    sortOrder?: "asc" | "desc";
                    /** @description Must be provided together with maxPrice */
                    minPrice?: string;
                    /** @description Must be provided together with minPrice */
                    maxPrice?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Products fetched successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                products: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                    _id: string;
                                    /** @example Wireless Mouse */
                                    title: string;
                                    /** @example 799 */
                                    price: number;
                                    /** @example Ergonomic wireless mouse with USB receiver */
                                    description: string;
                                    /** @example https://example.com/images/mouse.jpg */
                                    imageURL: string;
                                    /** @example 25 */
                                    stock: number;
                                    /** @example 12 */
                                    reviewCount: number;
                                    /** @example 54 */
                                    ratingSum: number;
                                    /** @example 4.5 */
                                    avgRating: number;
                                    /** @example 2026-01-15T10:00:00.000Z */
                                    createdAt: string;
                                    /** @example 2026-01-15T10:00:00.000Z */
                                    updatedAt: string;
                                }[];
                                pagination: {
                                    /** @example 42 */
                                    total: number;
                                    /** @example 1 */
                                    page: number;
                                    /** @example 10 */
                                    limit: number;
                                    /** @example 5 */
                                    totalPages: number;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single catalog product by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product fetched successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                _id: string;
                                /** @example Wireless Mouse */
                                title: string;
                                /** @example 799 */
                                price: number;
                                /** @example Ergonomic wireless mouse with USB receiver */
                                description: string;
                                /** @example https://example.com/images/mouse.jpg */
                                imageURL: string;
                                /** @example 25 */
                                stock: number;
                                /** @example 12 */
                                reviewCount: number;
                                /** @example 54 */
                                ratingSum: number;
                                /** @example 4.5 */
                                avgRating: number;
                                /** @example 2026-01-15T10:00:00.000Z */
                                createdAt: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the seller's own products (requires admin role) */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default 1) */
                    page?: string;
                    /** @description Items per page (default 10, max 100) */
                    limit?: string;
                    /** @description Searches title and description */
                    search?: string;
                    /** @description 'title' or omitted (defaults to newest first) */
                    sortBy?: string;
                    sortOrder?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Products fetched successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                products: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                    _id: string;
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3c */
                                    userId: string;
                                    /** @example false */
                                    isDeleted: boolean;
                                    /** @example Wireless Mouse */
                                    title: string;
                                    /** @example 799 */
                                    price: number;
                                    /** @example Ergonomic wireless mouse with USB receiver */
                                    description: string;
                                    /** @example https://example.com/images/mouse.jpg */
                                    imageURL: string;
                                    /** @example 25 */
                                    stock: number;
                                    /** @example 12 */
                                    reviewCount: number;
                                    /** @example 54 */
                                    ratingSum: number;
                                    /** @example 4.5 */
                                    avgRating: number;
                                    /** @example 2026-01-15T10:00:00.000Z */
                                    createdAt: string;
                                    /** @example 2026-01-15T10:00:00.000Z */
                                    updatedAt: string;
                                }[];
                                pagination: {
                                    /** @example 42 */
                                    total: number;
                                    /** @example 1 */
                                    page: number;
                                    /** @example 10 */
                                    limit: number;
                                    /** @example 5 */
                                    totalPages: number;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a product (requires admin role) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title: string;
                        price: number;
                        description: string;
                        imageURL: string;
                        stock: number;
                    };
                };
            };
            responses: {
                /** @description Product created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                _id: string;
                                /** @example 652f1c2e8b1d4e2a1c9e4b3c */
                                userId: string;
                                /** @example false */
                                isDeleted: boolean;
                                /** @example Wireless Mouse */
                                title: string;
                                /** @example 799 */
                                price: number;
                                /** @example Ergonomic wireless mouse with USB receiver */
                                description: string;
                                /** @example https://example.com/images/mouse.jpg */
                                imageURL: string;
                                /** @example 25 */
                                stock: number;
                                /** @example 12 */
                                reviewCount: number;
                                /** @example 54 */
                                ratingSum: number;
                                /** @example 4.5 */
                                avgRating: number;
                                /** @example 2026-01-15T10:00:00.000Z */
                                createdAt: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description Invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one of the seller's own products by id (requires admin role) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product fetched successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                _id: string;
                                /** @example 652f1c2e8b1d4e2a1c9e4b3c */
                                userId: string;
                                /** @example false */
                                isDeleted: boolean;
                                /** @example Wireless Mouse */
                                title: string;
                                /** @example 799 */
                                price: number;
                                /** @example Ergonomic wireless mouse with USB receiver */
                                description: string;
                                /** @example https://example.com/images/mouse.jpg */
                                imageURL: string;
                                /** @example 25 */
                                stock: number;
                                /** @example 12 */
                                reviewCount: number;
                                /** @example 54 */
                                ratingSum: number;
                                /** @example 4.5 */
                                avgRating: number;
                                /** @example 2026-01-15T10:00:00.000Z */
                                createdAt: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update one of the seller's own products (requires admin role) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title?: string;
                        price?: number;
                        description?: string;
                        imageURL?: string;
                        stock?: number;
                    };
                };
            };
            responses: {
                /** @description Product updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                _id: string;
                                /** @example 652f1c2e8b1d4e2a1c9e4b3c */
                                userId: string;
                                /** @example false */
                                isDeleted: boolean;
                                /** @example Wireless Mouse */
                                title: string;
                                /** @example 799 */
                                price: number;
                                /** @example Ergonomic wireless mouse with USB receiver */
                                description: string;
                                /** @example https://example.com/images/mouse.jpg */
                                imageURL: string;
                                /** @example 25 */
                                stock: number;
                                /** @example 12 */
                                reviewCount: number;
                                /** @example 54 */
                                ratingSum: number;
                                /** @example 4.5 */
                                avgRating: number;
                                /** @example 2026-01-15T10:00:00.000Z */
                                createdAt: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Soft-delete one of the seller's own products (requires admin role) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                _id: string;
                                /** @example 652f1c2e8b1d4e2a1c9e4b3c */
                                userId: string;
                                /** @example false */
                                isDeleted: boolean;
                                /** @example Wireless Mouse */
                                title: string;
                                /** @example 799 */
                                price: number;
                                /** @example Ergonomic wireless mouse with USB receiver */
                                description: string;
                                /** @example https://example.com/images/mouse.jpg */
                                imageURL: string;
                                /** @example 25 */
                                stock: number;
                                /** @example 12 */
                                reviewCount: number;
                                /** @example 54 */
                                ratingSum: number;
                                /** @example 4.5 */
                                avgRating: number;
                                /** @example 2026-01-15T10:00:00.000Z */
                                createdAt: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reviews for a product */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default 1) */
                    page?: string;
                    /** @description Items per page (default 10, max 100) */
                    limit?: string;
                    /** @description Filter by exact rating (1-5) */
                    rating?: string;
                    /** @description Defaults to newest */
                    sortBy?: "newest" | "rating_high" | "rating_low";
                };
                header?: never;
                path: {
                    /** @description Product id */
                    productId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reviews fetched successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                reviews: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3d */
                                    _id: string;
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3b */
                                    orderId: string;
                                    /** @example 5 */
                                    rating: number;
                                    /** @example Great product */
                                    title?: string;
                                    /** @example Works exactly as described, very happy with the purchase. */
                                    comment: string;
                                    /** @example 2026-01-15T10:00:00.000Z */
                                    createdAt: string;
                                    /** @example 2026-01-15T10:00:00.000Z */
                                    updatedAt: string;
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                    productId: string;
                                    userId: {
                                        /** @example 652f1c2e8b1d4e2a1c9e4b3c */
                                        _id: string;
                                        /** @example Jane Doe */
                                        name: string;
                                    };
                                }[];
                                pagination: {
                                    /** @example 42 */
                                    total: number;
                                    /** @example 1 */
                                    page: number;
                                    /** @example 10 */
                                    limit: number;
                                    /** @example 5 */
                                    totalPages: number;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a review for a product you have purchased */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product id */
                    productId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        rating: number;
                        title?: string;
                        comment: string;
                    };
                };
            };
            responses: {
                /** @description Review created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3d */
                                _id: string;
                                /** @example 652f1c2e8b1d4e2a1c9e4b3b */
                                orderId: string;
                                /** @example 5 */
                                rating: number;
                                /** @example Great product */
                                title?: string;
                                /** @example Works exactly as described, very happy with the purchase. */
                                comment: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                createdAt: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                updatedAt: string;
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                productId: string;
                                userId: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3c */
                                    _id: string;
                                    /** @example Jane Doe */
                                    name: string;
                                };
                            };
                        };
                    };
                };
                /** @description You can only review products you have purchased */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description You have already reviewed this product */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/reviews/{reviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single review */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product id */
                    productId: string;
                    /** @description Review id */
                    reviewId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Review fetched successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3d */
                                _id: string;
                                /** @example 652f1c2e8b1d4e2a1c9e4b3b */
                                orderId: string;
                                /** @example 5 */
                                rating: number;
                                /** @example Great product */
                                title?: string;
                                /** @example Works exactly as described, very happy with the purchase. */
                                comment: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                createdAt: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                updatedAt: string;
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                productId: string;
                                userId: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3c */
                                    _id: string;
                                    /** @example Jane Doe */
                                    name: string;
                                };
                            };
                        };
                    };
                };
                /** @description Review not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete your own review */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product id */
                    productId: string;
                    /** @description Review id */
                    reviewId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Review deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3d */
                                _id: string;
                                /** @example 652f1c2e8b1d4e2a1c9e4b3b */
                                orderId: string;
                                /** @example 5 */
                                rating: number;
                                /** @example Great product */
                                title?: string;
                                /** @example Works exactly as described, very happy with the purchase. */
                                comment: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                createdAt: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                updatedAt: string;
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                productId: string;
                                userId: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3c */
                                    _id: string;
                                    /** @example Jane Doe */
                                    name: string;
                                };
                            };
                        };
                    };
                };
                /** @description You can only modify your own review */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Review not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update your own review */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product id */
                    productId: string;
                    /** @description Review id */
                    reviewId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        rating?: number;
                        title?: string;
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description Review updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                /** @example 652f1c2e8b1d4e2a1c9e4b3d */
                                _id: string;
                                /** @example 652f1c2e8b1d4e2a1c9e4b3b */
                                orderId: string;
                                /** @example 5 */
                                rating: number;
                                /** @example Great product */
                                title?: string;
                                /** @example Works exactly as described, very happy with the purchase. */
                                comment: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                createdAt: string;
                                /** @example 2026-01-15T10:00:00.000Z */
                                updatedAt: string;
                                /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                productId: string;
                                userId: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3c */
                                    _id: string;
                                    /** @example Jane Doe */
                                    name: string;
                                };
                            };
                        };
                    };
                };
                /** @description You can only modify your own review */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Review not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/users/me/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's reviews */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default 1) */
                    page?: string;
                    /** @description Items per page (default 10, max 100) */
                    limit?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reviews fetched successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Success */
                            message: string;
                            data: {
                                reviews: {
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3d */
                                    _id: string;
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3b */
                                    orderId: string;
                                    /** @example 5 */
                                    rating: number;
                                    /** @example Great product */
                                    title?: string;
                                    /** @example Works exactly as described, very happy with the purchase. */
                                    comment: string;
                                    /** @example 2026-01-15T10:00:00.000Z */
                                    createdAt: string;
                                    /** @example 2026-01-15T10:00:00.000Z */
                                    updatedAt: string;
                                    /** @example 652f1c2e8b1d4e2a1c9e4b3c */
                                    userId: string;
                                    productId: {
                                        /** @example 652f1c2e8b1d4e2a1c9e4b3a */
                                        _id: string;
                                        /** @example Wireless Mouse */
                                        title: string;
                                        /** @example https://example.com/images/mouse.jpg */
                                        imageURL: string;
                                    };
                                }[];
                                pagination: {
                                    /** @example 42 */
                                    total: number;
                                    /** @example 1 */
                                    page: number;
                                    /** @example 10 */
                                    limit: number;
                                    /** @example 5 */
                                    totalPages: number;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
